// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Article/Article.tsx";
import * as $$$$$$2 from "./sections/Gallery.tsx";
import * as $$$$$$3 from "./sections/Theme/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/blog-do-ramils/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/blog-do-ramils/sections/Article/Article.tsx": $$$$$$1,
    "deco-sites/blog-do-ramils/sections/Gallery.tsx": $$$$$$2,
    "deco-sites/blog-do-ramils/sections/Theme/Theme.tsx": $$$$$$3,
  },
  "apps": {
    "deco-sites/blog-do-ramils/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/blog-do-ramils/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/blog-do-ramils",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
